version: '3.5'

services:
  proxy:
    image: nginx:1.17.9-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - dmz-network
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  dmz-network:
    external: true